name: Check

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm lint
